runtime: python38
automatic_scaling:
  min_instances: 1

includes:
  - environment.yaml

handlers:
- url: /api/.*
  secure: always
  script: auto
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /*
  static_dir: static
