application: gae-app-id
runtime: python27
version: 4
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: webwatcher.application
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /*
  static_dir: static
